// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ustayardım.Data;

#nullable disable

namespace ustayardım.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ustayardım.Data.Evulation_Table", b =>
                {
                    b.Property<int>("DegerlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DegerlendirmeDetaylari")
                        .HasColumnType("TEXT");

                    b.Property<int>("UstaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DegerlendirmeId");

                    b.ToTable("Evulation_Tables");
                });

            modelBuilder.Entity("ustayardım.Data.Galeri_Table", b =>
                {
                    b.Property<int>("GaleriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GaleriDetaylari")
                        .HasColumnType("TEXT");

                    b.Property<int>("UstaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GaleriId");

                    b.ToTable("Galeri_Tables");
                });

            modelBuilder.Entity("ustayardım.Data.Kategoriler", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriName")
                        .HasColumnType("TEXT");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("ustayardım.Data.Musteri_Table", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoriUstaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("ustayardım.Data.Sehirler", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("ustayardım.Data.User_Table", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .HasColumnType("TEXT");

                    b.Property<int>("IlId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSurname")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ustayardım.Data.Usta_Table", b =>
                {
                    b.Property<int>("UstaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hakkinda")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TamamlananIs")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UstaId");

                    b.ToTable("Ustalar");
                });

            modelBuilder.Entity("ustayardım.Data.Yorumlar_Table", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UstaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YorumDetaylari")
                        .HasColumnType("TEXT");

                    b.HasKey("YorumId");

                    b.ToTable("Yorumlar_Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
